services:

  db:
    image: mysql:8.1.0 
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: my_database
    ports: 
        - "3306:3306"    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db